-- MySQL Script generated by MySQL Workbench
-- Wed Feb 28 13:57:51 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Pesquisa_Eleitoral_Compilados
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Pesquisa_Eleitoral_Compilados
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Pesquisa_Eleitoral_Compilados` DEFAULT CHARACTER SET utf8 ;
USE `Pesquisa_Eleitoral_Compilados` ;

-- -----------------------------------------------------
-- Table `Pesquisa_Eleitoral_Compilados`.`ESTADOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pesquisa_Eleitoral_Compilados`.`ESTADOS` (
  `est_id` INT NOT NULL AUTO_INCREMENT,
  `est_sigla` CHAR(2) NOT NULL,
  PRIMARY KEY (`est_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pesquisa_Eleitoral_Compilados`.`MUNICIPIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pesquisa_Eleitoral_Compilados`.`MUNICIPIOS` (
  `mun_id` INT NOT NULL AUTO_INCREMENT,
  `mun_nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`mun_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pesquisa_Eleitoral_Compilados`.`CONTRATANTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pesquisa_Eleitoral_Compilados`.`CONTRATANTES` (
  `con_id` INT NOT NULL AUTO_INCREMENT,
  `con_nome` VARCHAR(155) NOT NULL,
  PRIMARY KEY (`con_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pesquisa_Eleitoral_Compilados`.`INSTITUTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pesquisa_Eleitoral_Compilados`.`INSTITUTOS` (
  `ins_id` INT NOT NULL AUTO_INCREMENT,
  `ins_nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ins_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pesquisa_Eleitoral_Compilados`.`ORGAOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pesquisa_Eleitoral_Compilados`.`ORGAOS` (
  `org_id` INT NOT NULL AUTO_INCREMENT,
  `org_nome` VARCHAR(45) NULL,
  `org_num_reg` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`org_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pesquisa_Eleitoral_Compilados`.`PESQUISAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pesquisa_Eleitoral_Compilados`.`PESQUISAS` (
  `pes_id` INT NOT NULL,
  `pes_ano` SMALLINT(4) UNSIGNED NOT NULL,
  `pes_cargo` VARCHAR(45) NULL,
  `pes_data` DATE NOT NULL,
  `pes_qnt_entrevistas` SMALLINT(5) NULL,
  `pes_margem_mais` DECIMAL(4,2) NULL,
  `pes_margem_menos` DECIMAL(4,2) NULL,
  `pes_est_id` INT NULL,
  `pes_mun_id` INT NULL,
  `pes_con_id` INT NULL,
  `pes_ins_id` INT NOT NULL,
  `pes_org_id` INT NOT NULL,
  PRIMARY KEY (`pes_id`),
  INDEX `fk_PESQUISAS_ESTADOS1_idx` (`pes_est_id` ASC) VISIBLE,
  INDEX `fk_PESQUISAS_MUNICIPIOS1_idx` (`pes_mun_id` ASC) VISIBLE,
  INDEX `fk_PESQUISAS_CONTRATANTES1_idx` (`pes_con_id` ASC) VISIBLE,
  INDEX `fk_PESQUISAS_INSTITUTOS1_idx` (`pes_ins_id` ASC) VISIBLE,
  INDEX `fk_PESQUISAS_ORGAOS1_idx` (`pes_org_id` ASC) VISIBLE,
  CONSTRAINT `fk_PESQUISAS_ESTADOS1`
    FOREIGN KEY (`pes_est_id`)
    REFERENCES `Pesquisa_Eleitoral_Compilados`.`ESTADOS` (`est_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PESQUISAS_MUNICIPIOS1`
    FOREIGN KEY (`pes_mun_id`)
    REFERENCES `Pesquisa_Eleitoral_Compilados`.`MUNICIPIOS` (`mun_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PESQUISAS_CONTRATANTES1`
    FOREIGN KEY (`pes_con_id`)
    REFERENCES `Pesquisa_Eleitoral_Compilados`.`CONTRATANTES` (`con_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PESQUISAS_INSTITUTOS1`
    FOREIGN KEY (`pes_ins_id`)
    REFERENCES `Pesquisa_Eleitoral_Compilados`.`INSTITUTOS` (`ins_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PESQUISAS_ORGAOS1`
    FOREIGN KEY (`pes_org_id`)
    REFERENCES `Pesquisa_Eleitoral_Compilados`.`ORGAOS` (`org_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pesquisa_Eleitoral_Compilados`.`ABORDAGENS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pesquisa_Eleitoral_Compilados`.`ABORDAGENS` (
  `abo_id` INT NOT NULL AUTO_INCREMENT,
  `ano_nome` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`abo_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pesquisa_Eleitoral_Compilados`.`PARTIDOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pesquisa_Eleitoral_Compilados`.`PARTIDOS` (
  `par_id` INT NOT NULL AUTO_INCREMENT,
  `par_sigla` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`par_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pesquisa_Eleitoral_Compilados`.`CANDIDATOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pesquisa_Eleitoral_Compilados`.`CANDIDATOS` (
  `can_id` INT NOT NULL,
  `can_nome` VARCHAR(255) NULL,
  `can_condicao` BINARY(1) NOT NULL,
  PRIMARY KEY (`can_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pesquisa_Eleitoral_Compilados`.`FILIACOES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pesquisa_Eleitoral_Compilados`.`FILIACOES` (
  `fil_par_id` INT NOT NULL,
  `fil_can_id` INT NOT NULL,
  `fil_pes_id` INT NOT NULL,
  PRIMARY KEY (`fil_par_id`, `fil_can_id`, `fil_pes_id`),
  INDEX `PFK_FIL_CAN_idx` (`fil_can_id` ASC) VISIBLE,
  INDEX `PFK_FIL_PES_idx` (`fil_pes_id` ASC) VISIBLE,
  CONSTRAINT `PFK_FIL_PAR`
    FOREIGN KEY (`fil_par_id`)
    REFERENCES `Pesquisa_Eleitoral_Compilados`.`PARTIDOS` (`par_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PFK_FIL_CAN`
    FOREIGN KEY (`fil_can_id`)
    REFERENCES `Pesquisa_Eleitoral_Compilados`.`CANDIDATOS` (`can_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PFK_FIL_PES`
    FOREIGN KEY (`fil_pes_id`)
    REFERENCES `Pesquisa_Eleitoral_Compilados`.`PESQUISAS` (`pes_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pesquisa_Eleitoral_Compilados`.`CENARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pesquisa_Eleitoral_Compilados`.`CENARIOS` (
  `cen_id` INT NOT NULL,
  `cen_descricao` VARCHAR(45) NULL,
  `cen_turno` TINYINT(2) NULL,
  `cen_voto_tipo` VARCHAR(30) NULL,
  `cen_pes_id` INT NOT NULL,
  `cen_abo_id` INT NOT NULL,
  PRIMARY KEY (`cen_id`),
  INDEX `FK_CEN_ABO_idx` (`cen_abo_id` ASC) VISIBLE,
  INDEX `FK_CEN_PES_idx` (`cen_pes_id` ASC) VISIBLE,
  CONSTRAINT `FK_CEN_ABO`
    FOREIGN KEY (`cen_abo_id`)
    REFERENCES `Pesquisa_Eleitoral_Compilados`.`ABORDAGENS` (`abo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_CEN_PES`
    FOREIGN KEY (`cen_pes_id`)
    REFERENCES `Pesquisa_Eleitoral_Compilados`.`PESQUISAS` (`pes_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pesquisa_Eleitoral_Compilados`.`PERCENTUAIS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pesquisa_Eleitoral_Compilados`.`PERCENTUAIS` (
  `per_can_id` INT NOT NULL,
  `per_cen_id` INT NOT NULL,
  `per_numero` DECIMAL(4,2) NOT NULL,
  PRIMARY KEY (`per_can_id`, `per_cen_id`),
  INDEX `PFK_PER_CEN_idx` (`per_cen_id` ASC) VISIBLE,
  CONSTRAINT `PFK_PER_CEN`
    FOREIGN KEY (`per_cen_id`)
    REFERENCES `Pesquisa_Eleitoral_Compilados`.`CENARIOS` (`cen_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PFK_PER_CAN`
    FOREIGN KEY (`per_can_id`)
    REFERENCES `Pesquisa_Eleitoral_Compilados`.`CANDIDATOS` (`can_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
